  name: Lint Check
  on: pull_request
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Java JDK
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'temurin'

        - name: Build with Gradle
          uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
          with:
            arguments: build

        - name: Run Lint check
          run: ./gradlew ktlintCheck

        - name: Install Ruby
          uses: danger/danger
          run: rbenv global 2.3.1 && gem install danger --version '~> 5.0' && danger

